/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_universidad.GUI;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import proyecto_univerisdad.BL.prounivBL2;
import proyecto_universidad.DAL.conexion;
import static proyecto_universidad.GUI.Login.profe;

/**
 *
 * @author Adry
 */
public class Modulo_Calificaciones extends javax.swing.JFrame {

    DefaultTableModel modelo;
    conexion conexion = new conexion();
    String matriculaAlum;

    /**
     * Creates new form Modulo_Calificaciones
     */
    public Modulo_Calificaciones() {
        initComponents();
        this.setLocationRelativeTo(null);

        /*Añadir valores al combo box*/
        mostrarDatosCBOBOX();

        mostrarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Horario = new javax.swing.JPanel();
        Calificaciones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Matricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txt_Parcial1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Parcial2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Parcial3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Ordinario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Extraordinario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_IdAsignatura = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cboGrupos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCalificacion = new javax.swing.JTable();
        txt_saludo_profesor = new javax.swing.JLabel();
        Encabezado3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(229, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        Horario.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jLabel1.setText("Matricula");

        txt_Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MatriculaActionPerformed(evt);
            }
        });

        jLabel2.setText("Parcial 1");

        jButton4.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/Boton.png"))); // NOI18N
        jButton4.setText("Ingresar");
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/BotonPressed.png"))); // NOI18N
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/OnBoton.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Parcial 2");

        jLabel4.setText("Parcial 3");

        jLabel5.setText("Ordinario");

        jLabel6.setText("Extraordinario");

        jLabel7.setText("Id asignatura");

        javax.swing.GroupLayout CalificacionesLayout = new javax.swing.GroupLayout(Calificaciones);
        Calificaciones.setLayout(CalificacionesLayout);
        CalificacionesLayout.setHorizontalGroup(
            CalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CalificacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalificacionesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalificacionesLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalificacionesLayout.createSequentialGroup()
                        .addComponent(txt_Matricula)
                        .addContainerGap())
                    .addComponent(txt_Parcial2)
                    .addComponent(txt_Parcial3)
                    .addComponent(txt_Ordinario)
                    .addComponent(txt_Extraordinario)
                    .addComponent(txt_Parcial1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CalificacionesLayout.createSequentialGroup()
                        .addComponent(txt_IdAsignatura)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalificacionesLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(CalificacionesLayout.createSequentialGroup()
                        .addGroup(CalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        CalificacionesLayout.setVerticalGroup(
            CalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalificacionesLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(CalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalificacionesLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel15))
                    .addGroup(CalificacionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_IdAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Parcial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Parcial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Parcial3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Ordinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Extraordinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jButton2.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/Boton.png"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/BotonPressed.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/OnBoton.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cboGrupos.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        cboGrupos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboGruposItemStateChanged(evt);
            }
        });
        cboGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGruposActionPerformed(evt);
            }
        });

        tbCalificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nombre", "Carrera", "Asignatura", "Parcial 1", "Parcial 2", "Parcial 3", "Ordinario", "Extraordinario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbCalificacion.getTableHeader().setReorderingAllowed(false);
        tbCalificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCalificacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCalificacion);
        if (tbCalificacion.getColumnModel().getColumnCount() > 0) {
            tbCalificacion.getColumnModel().getColumn(0).setResizable(false);
            tbCalificacion.getColumnModel().getColumn(1).setResizable(false);
            tbCalificacion.getColumnModel().getColumn(2).setResizable(false);
            tbCalificacion.getColumnModel().getColumn(3).setResizable(false);
            tbCalificacion.getColumnModel().getColumn(4).setResizable(false);
            tbCalificacion.getColumnModel().getColumn(4).setPreferredWidth(45);
            tbCalificacion.getColumnModel().getColumn(5).setResizable(false);
            tbCalificacion.getColumnModel().getColumn(5).setPreferredWidth(45);
            tbCalificacion.getColumnModel().getColumn(6).setResizable(false);
            tbCalificacion.getColumnModel().getColumn(6).setPreferredWidth(45);
            tbCalificacion.getColumnModel().getColumn(7).setResizable(false);
            tbCalificacion.getColumnModel().getColumn(7).setPreferredWidth(50);
            tbCalificacion.getColumnModel().getColumn(8).setResizable(false);
            tbCalificacion.getColumnModel().getColumn(8).setPreferredWidth(50);
        }

        txt_saludo_profesor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_saludo_profesor.setText("Bienvenido profesor ");

        javax.swing.GroupLayout HorarioLayout = new javax.swing.GroupLayout(Horario);
        Horario.setLayout(HorarioLayout);
        HorarioLayout.setHorizontalGroup(
            HorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HorarioLayout.createSequentialGroup()
                .addGroup(HorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HorarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HorarioLayout.createSequentialGroup()
                                .addComponent(txt_saludo_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HorarioLayout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(HorarioLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Calificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HorarioLayout.setVerticalGroup(
            HorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HorarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(HorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_saludo_profesor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Calificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Encabezado3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setFont(new java.awt.Font("Corbel", 0, 48)); // NOI18N
        jLabel16.setText("UNIVERSIDAD DEL MONTE");

        javax.swing.GroupLayout Encabezado3Layout = new javax.swing.GroupLayout(Encabezado3);
        Encabezado3.setLayout(Encabezado3Layout);
        Encabezado3Layout.setHorizontalGroup(
            Encabezado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Encabezado3Layout.createSequentialGroup()
                .addGroup(Encabezado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Encabezado3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel16))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Encabezado3Layout.setVerticalGroup(
            Encabezado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Encabezado3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(Encabezado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Encabezado3Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Encabezado3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(37, 37, 37)))
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Encabezado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Horario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Encabezado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Horario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGruposActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboGruposActionPerformed

    private void cboGruposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboGruposItemStateChanged
        // TODO add your handling code here:
        String asignatura = (String) cboGrupos.getSelectedItem();
        System.out.println(asignatura);

        this.limpiarTabla();
        filtrar(asignatura);

    }//GEN-LAST:event_cboGruposItemStateChanged

    private void txt_MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MatriculaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String matricula, asignatura;
        if (txt_Matricula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No puede dejar el campo vacío.");
        } else {
            ResultSet resultado = null;
            resultado = conexion.consultarRegistros("SELECT Alumnos_Matricula_alumno, Asignaturas_Id_Asignatura FROM calificaciones");

            try {
                prounivBL2 datos = obtenerDatos();
                while (resultado.next()) {
                    matricula = resultado.getString("Alumnos_Matricula_alumno");
                    asignatura = resultado.getString("Asignaturas_Id_Asignatura");
                    if (datos.getMatricula().equals(resultado.getString("Alumnos_Matricula_alumno")) && datos.getAsignatura().equals(resultado.getString("Asignaturas_Id_Asignatura"))) {
                        String strSentenciaInsert = String.format("UPDATE calificaciones SET Parcial_1 = '%s',Parcial_2 = '%s',Parcial_3 = '%s', Ordinario = '%s',Extraordinario = '%s' WHERE Alumnos_Matricula_alumno = '%s' and Asignaturas_Id_Asignatura='%s'", datos.getParcial1(), datos.getParcial2(), datos.getParcial3(), datos.getOrdinario(), datos.getExtraordinario(), matricula, asignatura);
                        conexion.ejecutarSentenciaSQL(strSentenciaInsert);
                        this.limpiarTabla();
                        this.mostrarDatos();//actualizamos la tabla
                        this.LimpiarGUI();
                    }
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbCalificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCalificacionMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();

            matriculaAlum = receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString();
            txt_Matricula.setText(matriculaAlum);

            String idAsig = GetIdAsignatura(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            txt_IdAsignatura.setText(idAsig);

            txt_Parcial1.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
            txt_Parcial2.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            txt_Parcial3.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 6).toString());
            txt_Ordinario.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 7).toString());
            txt_Extraordinario.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 8).toString());

        }
    }//GEN-LAST:event_tbCalificacionMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "¿Desea salir de calificaciones?", "Mensaje de confirmación", JOptionPane.YES_OPTION);
        if (res == 0) {
            Modulo_Profesor mp= new Modulo_Profesor();
            mp.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    String GetIdAsignatura(String nameAsig) {

        String a = null;
        String sql = String.format("SELECT Id_Asignatura FROM asignaturas WHERE Nombre='%s'", nameAsig);
        ResultSet rs = conexion.consultarRegistros(sql);
        try {
            while (rs.next()) {
                a = rs.getString("Id_Asignatura");
            }
            //tbGrado.setModel(modelo);
        } catch (Exception e) {
        }
        return a;
    }

    void limpiarTabla() {
        modelo = (DefaultTableModel) tbCalificacion.getModel();
        modelo.setRowCount(0);
    }

    void LimpiarGUI() {
        txt_Matricula.setText("");
        txt_Parcial1.setText("");
        txt_Parcial2.setText("");
        txt_Parcial3.setText("");
        txt_Ordinario.setText("");
        txt_Extraordinario.setText("");
        txt_IdAsignatura.setText("");
    }

    public prounivBL2 obtenerDatos() {
        prounivBL2 datos = new prounivBL2();

        String matricula = txt_Matricula.getText().trim();
        String parcial1 = txt_Parcial1.getText().trim();
        String parcial2 = txt_Parcial2.getText().trim();
        String parcial3 = txt_Parcial3.getText().trim();
        String ordinario = txt_Ordinario.getText().trim();
        String extraordinario = txt_Extraordinario.getText();
        String idAsignatura = txt_IdAsignatura.getText();

        datos.setMatricula(matricula);
        datos.setParcial1(parcial1);
        datos.setParcial2(parcial2);
        datos.setParcial3(parcial3);
        datos.setOrdinario(ordinario);
        datos.setExtraordinario(extraordinario);
        datos.setAsignatura(idAsignatura);

        return datos;
    }

    private void filtrar(String seleccion) {
        String sql = "SELECT calificaciones.Alumnos_Matricula_alumno, alumnos.Nombre, carreras.Nombre, asignaturas.Nombre, calificaciones.Parcial_1, calificaciones.Parcial_2, calificaciones.Parcial_3, calificaciones.Ordinario, calificaciones.Extraordinario FROM calificaciones, alumnos, asignaturas, carreras WHERE calificaciones.Alumnos_Matricula_alumno=alumnos.Matricula_alumno and calificaciones.Asignaturas_Id_Asignatura= asignaturas.Id_Asignatura and alumnos.Carreras_Id_Carrera=carreras.Id_Carrera and asignaturas.Nombre='" + seleccion + "' ";
        ResultSet rs = conexion.consultarRegistros(sql);
        try {
            Object[] horario = new Object[9];
            modelo = (DefaultTableModel) tbCalificacion.getModel();
            while (rs.next()) {
                horario[0] = rs.getString("calificaciones.Alumnos_Matricula_alumno");
                horario[1] = rs.getString("alumnos.Nombre");
                horario[2] = rs.getString("carreras.Nombre");
                horario[3] = rs.getString("asignaturas.Nombre");
                horario[4] = rs.getFloat("calificaciones.Parcial_1");
                horario[5] = rs.getFloat("calificaciones.Parcial_2");
                horario[6] = rs.getFloat("calificaciones.Parcial_3");
                horario[7] = rs.getFloat("calificaciones.Ordinario");
                horario[8] = rs.getFloat("calificaciones.Extraordinario");
                modelo.addRow(horario);
            }
            //tbGrado.setModel(modelo);
        } catch (Exception e) {
        }
    }

    private void mostrarDatosCBOBOX() {
        cboGrupos.addItem("Todas las asignaturas");
        String sql = "SELECT Nombre FROM asignaturas";
        ResultSet rs = conexion.consultarRegistros(sql);
        try {

            while (rs.next()) {
                cboGrupos.addItem(rs.getString("Nombre"));
            }
            //tbGrado.setModel(modelo);
        } catch (Exception e) {
        }
    }

    void mostrarDatos() {
        String idProf = profe;
        String sql = String.format("SELECT calificaciones.Alumnos_Matricula_alumno, alumnos.Nombre, carreras.Nombre, asignaturas.Nombre, calificaciones.Parcial_1, calificaciones.Parcial_2, calificaciones.Parcial_3, calificaciones.Ordinario, calificaciones.Extraordinario FROM calificaciones, alumnos, asignaturas, carreras WHERE calificaciones.Alumnos_Matricula_alumno=alumnos.Matricula_alumno and calificaciones.Asignaturas_Id_Asignatura= asignaturas.Id_Asignatura and alumnos.Carreras_Id_Carrera=carreras.Id_Carrera and Profesores_Matricula_Profesor='%s'", idProf);
        ResultSet rs = conexion.consultarRegistros(sql);
        try {
            Object[] horario = new Object[9];
            modelo = (DefaultTableModel) tbCalificacion.getModel();
            while (rs.next()) {
                horario[0] = rs.getString("calificaciones.Alumnos_Matricula_alumno");
                horario[1] = rs.getString("alumnos.Nombre");
                horario[2] = rs.getString("carreras.Nombre");
                horario[3] = rs.getString("asignaturas.Nombre");
                horario[4] = rs.getFloat("calificaciones.Parcial_1");
                horario[5] = rs.getFloat("calificaciones.Parcial_2");
                horario[6] = rs.getFloat("calificaciones.Parcial_3");
                horario[7] = rs.getFloat("calificaciones.Ordinario");
                horario[8] = rs.getFloat("calificaciones.Extraordinario");
                modelo.addRow(horario);
            }
            //tbGrado.setModel(modelo);
        } catch (Exception e) {
        }

        /*Codigo para el saludo del profesor*/
        String sql2 = String.format("SELECT Nombre, Apellido_paterno, Apellido_materno, Id_genero FROM profesores WHERE Matricula_profesor='%s'", idProf);
        String saludo = "";
        ResultSet rs2 = conexion.consultarRegistros(sql2);
        try {
            System.out.println("1");
            Object[] name = new Object[4];
            while (rs2.next()) {
                name[0] = rs2.getString("Nombre");
                name[1] = rs2.getString("Apellido_paterno");
                name[2] = rs2.getString("Apellido_materno");
                name[3] = rs2.getInt("Id_genero");

                if (Integer.parseInt(name[3].toString()) == 1) {
                    saludo = "Bienvenido Profesor " + name[0].toString() + " " + name[1].toString() + " " + name[2].toString();
                } else {
                    saludo = "Bienvenida Profesora " + name[0].toString() + " " + name[1].toString() + " " + name[2].toString();
                }
                txt_saludo_profesor.setText(saludo);
            }
            //tbGrado.setModel(modelo);
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo_Calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo_Calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo_Calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo_Calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo_Calificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Calificaciones;
    private javax.swing.JPanel Encabezado3;
    private javax.swing.JPanel Horario;
    private javax.swing.JComboBox<String> cboGrupos;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCalificacion;
    private javax.swing.JTextField txt_Extraordinario;
    private javax.swing.JTextField txt_IdAsignatura;
    private javax.swing.JTextField txt_Matricula;
    private javax.swing.JTextField txt_Ordinario;
    private javax.swing.JTextField txt_Parcial1;
    private javax.swing.JTextField txt_Parcial2;
    private javax.swing.JTextField txt_Parcial3;
    private javax.swing.JLabel txt_saludo_profesor;
    // End of variables declaration//GEN-END:variables
}
