/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_universidad.GUI;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import proyecto_universidad.DAL.conexion;

/**
 *
 * @author luisl
 */
public class Modulo_Admin_Grupos extends javax.swing.JFrame {

    DefaultTableModel modelo;
    conexion conexion = new conexion();

    public Modulo_Admin_Grupos() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarDatos();
        cbx_asig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_grupo = new javax.swing.JTable();
        Datos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_idgrupo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_aula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_capacidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbx_asignatura = new javax.swing.JComboBox<>();
        Botones = new javax.swing.JPanel();
        btn_ingresar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Encabezado.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 48)); // NOI18N
        jLabel2.setText("UNIVERSIDAD DEL MONTE");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/barra.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/Logo_Universidad.png"))); // NOI18N

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2))
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        Contenido.setBackground(new java.awt.Color(204, 204, 255));

        Tb_grupo.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        Tb_grupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id grupo", "Aula", "Capacidad", "Asignatura"
            }
        ));
        Tb_grupo.getTableHeader().setReorderingAllowed(false);
        Tb_grupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_grupoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_grupo);
        if (Tb_grupo.getColumnModel().getColumnCount() > 0) {
            Tb_grupo.getColumnModel().getColumn(0).setResizable(false);
            Tb_grupo.getColumnModel().getColumn(1).setResizable(false);
            Tb_grupo.getColumnModel().getColumn(2).setResizable(false);
            Tb_grupo.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel4.setText("Id grupo:");

        txt_idgrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idgrupoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel1.setText("Aula:");

        txt_aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_aulaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel7.setText("Capacidad:");

        txt_capacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_capacidadActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel9.setText("Asignatura:");

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DatosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(txt_capacidad)
                    .addComponent(jLabel7)
                    .addComponent(txt_aula)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txt_idgrupo)
                    .addComponent(cbx_asignatura, 0, 185, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(txt_idgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_asignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        Botones.setBackground(new java.awt.Color(153, 153, 255));

        btn_ingresar.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        btn_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/Boton.png"))); // NOI18N
        btn_ingresar.setText("Ingresar");
        btn_ingresar.setContentAreaFilled(false);
        btn_ingresar.setFocusPainted(false);
        btn_ingresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ingresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/BotonPressed.png"))); // NOI18N
        btn_ingresar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/OnBoton.png"))); // NOI18N
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_actualizar.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/Boton.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setContentAreaFilled(false);
        btn_actualizar.setFocusPainted(false);
        btn_actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_actualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/BotonPressed.png"))); // NOI18N
        btn_actualizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/OnBoton.png"))); // NOI18N
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/Boton.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setContentAreaFilled(false);
        btn_eliminar.setFocusPainted(false);
        btn_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/BotonPressed.png"))); // NOI18N
        btn_eliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/OnBoton.png"))); // NOI18N
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonesLayout = new javax.swing.GroupLayout(Botones);
        Botones.setLayout(BotonesLayout);
        BotonesLayout.setHorizontalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        BotonesLayout.setVerticalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ingresar)
                    .addComponent(btn_actualizar)
                    .addComponent(btn_eliminar))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel5.setText("Administración de grupos.");

        btn_regresar.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/Boton.png"))); // NOI18N
        btn_regresar.setText("Regresar");
        btn_regresar.setContentAreaFilled(false);
        btn_regresar.setFocusPainted(false);
        btn_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_regresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/BotonPressed.png"))); // NOI18N
        btn_regresar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/OnBoton.png"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_regresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addComponent(btn_regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idgrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idgrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idgrupoActionPerformed

    private void txt_aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_aulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_aulaActionPerformed

    private void txt_capacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_capacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_capacidadActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // Boton de actualizar
        String id_grupo = txt_idgrupo.getText();
        String aula = txt_aula.getText();
        String capacidad = txt_capacidad.getText();
        int asignatura = obtenerid_asig(cbx_asignatura.getSelectedItem().toString());

        try {

            if (id_grupo.equals("") || aula.equals("") || capacidad.equals("") || asignatura==0) {
                JOptionPane.showMessageDialog(this, "Faltan ingresar datos");
            } else {
                String sql = String.format("UPDATE `grupos` SET `Aula` = '%s',`Capacidad` = '%s',`Asignaturas_Id_Asignatura` = '%d' WHERE Id_Grupo = '%s'", aula, capacidad, asignatura, id_grupo);
                conexion.ejecutarSentenciaSQL(sql);
                JOptionPane.showMessageDialog(this, "Datos modificados correctamente");
                this.limpiarTabla();
                this.mostrarDatos();//actualizamos la tabla
                this.LimpiarGUI();
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void Tb_grupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_grupoMouseClicked
        //evento al darle clic a una fila de la tabla
        if (evt.getClickCount() == -1) {
            JOptionPane.showMessageDialog(this, "No se seleccionó fila");

        } else {
            JTable receptor = (JTable) evt.getSource();
            txt_idgrupo.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txt_aula.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            txt_capacidad.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            String id_asig= Nom_asignatura(Integer.parseInt(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString()));
            cbx_asignatura.setSelectedItem(id_asig);
        
        }
        
    }//GEN-LAST:event_Tb_grupoMouseClicked

     String Nom_asignatura(int id_asig){
        
        String a = null;        
        String sql = String.format("Select Nombre from asignaturas where Id_Asignatura = '%s' ", id_asig);       
        ResultSet rs = conexion.consultarRegistros(sql);
        try {           
            while(rs.next()){
                a = rs.getString("Nombre");
            }
            //tbGrado.setModel(modelo);
        } catch (Exception e) {
        }
        return a;
    }
    
    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // regresar a administrador
        int res = JOptionPane.showConfirmDialog(null, "¿Desea salir de administración de 'Grupos'?", "Mensaje de confirmación", JOptionPane.YES_OPTION);
        if (res == 0) {
            Modulo_Administrador Admin = new Modulo_Administrador();
            Admin.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // BOTON DE AGREGAR
        //Creamos variables para colocar la nueva informacion a ingresar.
        String id_grupo = txt_idgrupo.getText();
        String aula = txt_aula.getText();
        String capacidad = txt_capacidad.getText();
        int asignatura = obtenerid_asig(cbx_asignatura.getSelectedItem().toString());

        try {

            if (id_grupo.equals("") || aula.equals("") || capacidad.equals("") || asignatura==0) {
                JOptionPane.showMessageDialog(this, "Faltan ingresar datos");
            } else {
                String sql=String.format("INSERT INTO `grupos`(`Id_Grupo`,`Aula`,`Capacidad`,`Asignaturas_Id_Asignatura`) "
                                + "VALUES ('%s', '%s', '%s', '%d')", id_grupo, aula, capacidad,asignatura);
                conexion.ejecutarSentenciaSQL(sql);
                JOptionPane.showMessageDialog(this, "Datos agregados correctamente");
                this.limpiarTabla();
                this.mostrarDatos();//actualizamos la tabla
                this.LimpiarGUI();
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        //Boton eliminar
        String id_grupo = txt_idgrupo.getText();
        int fila = Tb_grupo.getSelectedRow();
        try {
            if (fila < 0) {
                JOptionPane.showMessageDialog(this, "Fila no seleccionada");
            } else {
                int res = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este campo?", "Mensaje de confirmación", JOptionPane.YES_OPTION);
                if (res == 0) {
                    String sql = String.format("DELETE FROM `grupos` WHERE Id_Grupo = '%s'", id_grupo);
                    conexion.ejecutarSentenciaSQL(sql);//hace consulta y agrega a la tabla
                    this.limpiarTabla();
                    this.mostrarDatos();
                    this.LimpiarGUI();
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    int obtenerid_asig(String asig){
        int a=0;        
        String sql = String.format("Select Id_Asignatura from asignaturas where Nombre = '%s' ", asig);       
        ResultSet rs = conexion.consultarRegistros(sql);
        try {           
            while(rs.next()){
                a = rs.getInt("Id_Asignatura");
            }
            //tbGrado.setModel(modelo);
        } catch (Exception e) {
        }
        return a;
    }
    //METODOS
    void LimpiarGUI() {
        txt_idgrupo.setText("");
        txt_aula.setText("");
        txt_capacidad.setText("");
        cbx_asignatura.setSelectedIndex(0);
    }

    void limpiarTabla() {
        modelo.setNumRows(0);
    }

    void mostrarDatos() {
        String sql = "Select * from grupos";
        ResultSet rs = conexion.consultarRegistros(sql);
        try {
            Object[] grupos = new Object[4];
            modelo = (DefaultTableModel) Tb_grupo.getModel();
            while (rs.next()) {
                grupos[0] = rs.getString("Id_Grupo");
                grupos[1] = rs.getString("Aula");
                grupos[2] = rs.getInt("Capacidad");
                grupos[3] = rs.getInt("Asignaturas_Id_Asignatura");
                modelo.addRow(grupos);
            }
            Tb_grupo.setModel(modelo);
        } catch (Exception e) {
        }
    }

    //METODO PARA MOSTRAR ITEMS DEL COMBO BOX DE ASIGNATURAS
    void cbx_asig() {
        String sql = "Select Nombre from asignaturas";

        try {
            ResultSet rs = conexion.consultarRegistros(sql);
            cbx_asignatura.addItem("Seleccione una opción");
            while (rs.next()) {

                cbx_asignatura.addItem(rs.getString("Nombre"));

            }
        } catch (SQLException e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo_Admin_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo_Admin_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo_Admin_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo_Admin_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo_Admin_Grupos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botones;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Datos;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel Principal;
    private javax.swing.JTable Tb_grupo;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JComboBox<String> cbx_asignatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_aula;
    private javax.swing.JTextField txt_capacidad;
    private javax.swing.JTextField txt_idgrupo;
    // End of variables declaration//GEN-END:variables
}
