/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_universidad.GUI;

import java.sql.Blob;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import proyecto_univerisdad.BL.prounivBL2;
import proyecto_universidad.DAL.conexion;

/**
 *
 * @author erick
 */
public class Modulo_Admin_Aspirantes extends javax.swing.JFrame {

    DefaultTableModel modelo;
    conexion conexion = new conexion();

    public Modulo_Admin_Aspirantes() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAspirantes = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_ApellidoP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ApellidoM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Curp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(993, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(993, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(993, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(135, 135, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1000, 10));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(780, 169));

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 48)); // NOI18N
        jLabel6.setText("UNIVERSIDAD FRANCISCO");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/Logo_Universidad.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/barra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel7)
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGap(7, 7, 7)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 150));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ASPIRANTES");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 560, 40));

        jButton10.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/Boton.png"))); // NOI18N
        jButton10.setText("Regresar");
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/BotonPressed.png"))); // NOI18N
        jButton10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/OnBoton.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 150, 30));

        tbAspirantes.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        tbAspirantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido paterno", "Apellido materno", "CURP", "Certificado de prepa", "Cita", "Curp", "Acta de nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbAspirantes.getTableHeader().setReorderingAllowed(false);
        tbAspirantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAspirantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbAspirantes);
        if (tbAspirantes.getColumnModel().getColumnCount() > 0) {
            tbAspirantes.getColumnModel().getColumn(0).setResizable(false);
            tbAspirantes.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbAspirantes.getColumnModel().getColumn(1).setResizable(false);
            tbAspirantes.getColumnModel().getColumn(2).setResizable(false);
            tbAspirantes.getColumnModel().getColumn(3).setResizable(false);
            tbAspirantes.getColumnModel().getColumn(3).setPreferredWidth(50);
            tbAspirantes.getColumnModel().getColumn(4).setResizable(false);
            tbAspirantes.getColumnModel().getColumn(5).setResizable(false);
            tbAspirantes.getColumnModel().getColumn(5).setPreferredWidth(40);
            tbAspirantes.getColumnModel().getColumn(6).setResizable(false);
            tbAspirantes.getColumnModel().getColumn(6).setPreferredWidth(40);
            tbAspirantes.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 710, 270));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(135, 135, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 10));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        txt_Nombre.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel6.add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 180, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel3.setText("Apellido paterno:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        txt_ApellidoP.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txt_ApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoPActionPerformed(evt);
            }
        });
        jPanel6.add(txt_ApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel4.setText("CURP");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txt_ApellidoM.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel6.add(txt_ApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 180, -1));

        jLabel9.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel9.setText("Apellido materno:");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel6.add(txt_Curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, -1));

        jButton1.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/Boton.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/BotonPressed.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/OnBoton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 150, -1));

        jButton2.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/Boton.png"))); // NOI18N
        jButton2.setText("Rechazar");
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/BotonPressed.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_universidad/Imagenes/OnBoton.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 150, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 260, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Modulo_Administrador mdAdm = new Modulo_Administrador();
        mdAdm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txt_ApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoPActionPerformed

    private void tbAspirantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAspirantesMouseClicked
        prounivBL2 datos = new prounivBL2();
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();

            txt_Nombre.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txt_ApellidoP.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            txt_ApellidoM.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txt_Curp.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            datos.setCertificado((Blob) receptor.getModel().getValueAt(receptor.getSelectedRow(), 4));
            datos.setCita((Blob) receptor.getModel().getValueAt(receptor.getSelectedRow(), 5));
            datos.setCurpD((Blob) receptor.getModel().getValueAt(receptor.getSelectedRow(), 6));
            datos.setActaN((Blob) receptor.getModel().getValueAt(receptor.getSelectedRow(), 7));
            
        }
    }//GEN-LAST:event_tbAspirantesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int res =JOptionPane.showConfirmDialog(null, "¿Desea rechazar a este estudiante?");
        if(res == 0){   
            prounivBL2 datos = obtenerDatos();

            
            String strSentenciaInsert = String.format("DELETE FROM `inscripciones` WHERE `Id_Inscripcion` = '%s'",datos.getIdInscripcion());
            conexion.ejecutarSentenciaSQL(strSentenciaInsert);//hace consulta y agrega a la tabla
            this.limpiarTabla();
            this.mostrarDatos();
            this.LimpiarGUI();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int res =JOptionPane.showConfirmDialog(null, "¿Desea aceptar a este estudiante?");
        if(res == 0){   
            prounivBL2 datos = obtenerDatos();

            String matricula=generarMatricula(datos.getCurp());
            String password = generarPassword();
            int semestre = 1;
            int year_ingreso = 2022;
            float avance = 0;
            int idGenero=getGenero(datos.getIdInscripcion());
            int idCarrea=getCarrera(datos.getIdInscripcion());
            
            String strSentenciaInsert = String.format("INSERT INTO `alumnos`(`Matricula_alumno`, `Nombre`, `Apellido_paterno`, `Apellido_materno`, `Semestre`, `Ano_ingreso`, `Avance_curricular`, `Contrasena`, `Carreras_Id_Carrera`, `Id_genero`, `Id_categoria`) VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')",matricula, datos.getNombre(), datos.getApellidoP(), datos.getApellidoM(), semestre, year_ingreso, avance, password, idCarrea, idGenero, 3);
            conexion.ejecutarSentenciaSQL(strSentenciaInsert);
            
            String strSetenciaInsert2 = String.format("INSERT INTO `documentosalumnos`(`Certificado_preparatorio`, `Cita`, `Curp`, `Acta_nacimiento`, `Alumnos_Matricula_alumno`, `CurpString`) VALUES ('%s', '%s', '%s', '%s', '%s', '%s')",datos.getCertificado(),datos.getCita(), datos.getCurpD(), datos.getActaN(), matricula , datos.getCurp() );
            conexion.ejecutarSentenciaSQL(strSetenciaInsert2);
                    
            String strSentenciaDelete = String.format("DELETE FROM `inscripciones` WHERE `Id_Inscripcion` = '%s'",datos.getIdInscripcion());
            conexion.ejecutarSentenciaSQL(strSentenciaDelete);
           
            this.limpiarTabla();
            this.mostrarDatos();
            this.LimpiarGUI();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private String generarMatricula(String curp){
        String matricula="";
        for(int i=0; i<=9; i++){
            matricula+=curp.charAt(i);
        }
        return matricula;
    }
    private String generarPassword(){
    /*Hay que recordar que la contraseña es un varchar de 8*/
    String password="";
    Random random = new Random();
    String cadena = "abcdefghijklmnñopqrstuvwxyz0123456789";
    
    for(int i=0; i<=7; i++){
        int randomInt = random.nextInt(cadena.length());
        password+= cadena.charAt(randomInt);
    }
        
    
    return password;
    }
    private int getIdInscripcion(String name, String curp){
        
        int a = 0;        
        String sql = String.format("SELECT Id_Inscripcion FROM `inscripciones` WHERE Nombre='%s' and CurpString='%s'", name, curp);       
        ResultSet rs = conexion.consultarRegistros(sql);
        try {           
            while(rs.next()){
                a = Integer.parseInt(rs.getString("Id_Inscripcion"));
            }
            //tbGrado.setModel(modelo);
        } catch (Exception e) {
        }
        return a;
    }
    private void LimpiarGUI(){
        txt_Nombre.setText("");            
        txt_ApellidoP.setText("");           
        txt_ApellidoM.setText("");
        txt_Curp.setText("");
    }
    private void limpiarTabla(){
        modelo.setNumRows(0);
    }
    private int getGenero(int idInscripcion){
        int a = 0;        
        String sql = String.format("Select id_genero from inscripciones where Id_Inscripcion='%s'", idInscripcion);       
        ResultSet rs = conexion.consultarRegistros(sql);
        try {           
            while(rs.next()){
                a = Integer.parseInt(rs.getString("Id_genero"));
            }
            //tbGrado.setModel(modelo);
        } catch (Exception e) {
        }
        return a;
    }
    private int getCarrera(int idInscripcion){
        int a = 0;        
        String sql = String.format("Select Carreras_Id_Carrera from inscripciones where Id_Inscripcion='%s'", idInscripcion);       
        ResultSet rs = conexion.consultarRegistros(sql);
        try {           
            while(rs.next()){
                a = Integer.parseInt(rs.getString("Carreras_Id_Carrera"));
            }
            //tbGrado.setModel(modelo);
        } catch (Exception e) {
        }
        return a;
    }
    private void mostrarDatos() {
        String sql = "SELECT * FROM `inscripciones`";
        ResultSet rs = conexion.consultarRegistros(sql);
        try {
            Object[] aspirantes = new Object[8];
            modelo = (DefaultTableModel) tbAspirantes.getModel();
            while (rs.next()) {
                aspirantes[0] = rs.getString("Nombre");
                aspirantes[1] = rs.getString("Apellido_paterno");
                aspirantes[2] = rs.getString("Apellido_materno");
                aspirantes[3] = rs.getString("CurpString");
                aspirantes[4] = rs.getBlob("Certificado_preparatoria");
                aspirantes[5] = rs.getBlob("Cita");
                aspirantes[6] = rs.getBlob("Curp");
                aspirantes[7] = rs.getBlob("Acta_nacimiento");
                
                
                modelo.addRow(aspirantes);
            }
            //tbGrado.setModel(modelo);
        } catch (Exception e) {
        }
    }

    public prounivBL2 obtenerDatos() {
        prounivBL2 datos = new prounivBL2();
  
        String nombre = txt_Nombre.getText().trim();
        String apellidoP = txt_ApellidoP.getText().trim();
        String apellidoM = txt_ApellidoM.getText().trim();
        String curp = txt_Curp.getText().trim();
        
        

        int id = getIdInscripcion(nombre,curp);
        datos.setNombre(nombre);
        datos.setApellidoP(apellidoP);
        datos.setApellidoM(apellidoM);
        datos.setCurp(curp);
        datos.setIdInscripcion(id);
        
        datos.setGenero(0);
        datos.setIdCarrera(0);
        return datos;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo_Admin_Aspirantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo_Admin_Aspirantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo_Admin_Aspirantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo_Admin_Aspirantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo_Admin_Aspirantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbAspirantes;
    private javax.swing.JTextField txt_ApellidoM;
    private javax.swing.JTextField txt_ApellidoP;
    private javax.swing.JTextField txt_Curp;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
